apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: <YOUR USER>-kafka-cluster
  namespace: <YOUR USER>
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    resources:
      limits:
        cpu: '4'
        memory: 8Gi
      requests:
        cpu: '2'
        memory: 6Gi
    config:
      default.replication.factor: 3
      inter.broker.protocol.version: '3.7'
      min.insync.replicas: 2
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    authorization:
      type: simple
    listeners:
      - name: plain
        port: 9092
        tls: false
        type: internal
      - name: tls
        port: 9093
        tls: true
        type: internal
      - name: external
        port: 9094
        type: route
        tls: true
        authentication:
          type: scram-sha-512
    jvmOptions:
      '-XX':
        InitiatingHeapOccupancyPercent: "45"
        MaxGCPauseMillis: "200"
        UseG1GC: "true"
        UseStringDeduplication: "true"
      '-Xms': 6g
      '-Xmx': 6g
      gcLoggingEnabled: true
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: kafka-metrics-config.yml
          name: kafka-metrics
    replicas: 3
    storage:
      class: gp3-csi
      deleteClaim: true
      size: 20Gi
      type: persistent-claim
    version: 3.7.0
  kafkaExporter:
    groupRegex: ".*"
    topicRegex: ".*"
  zookeeper:
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: zookeeper-metrics-config.yml
          name: kafka-metrics
    replicas: 3
    storage:
      class: gp3-csi
      size: 10Gi
      type: persistent-claim